### ISSUE TITLE
Langfuse integration

### ISSUE THREAD

**Issue by kongzii** [galatolofederico/microchain#16]
Hi, we are now integrating [Langfuse](https://langfuse.com/) into our non-microchain agents, and so far, it seems like a great library for monitoring LLMs.

Would you be interested in having built-in support for Langfuse?

I'm not sure how big changes it would introduce into Microchain, but most probably it wouldn't be so bad.

If that's something you'd like, I could implement it sometime next week. If not, I'd find a way how to use it without modifying Microchain itself.

**Comment by galatolofederico** [comment]
That would be great thanks a lot! If it's not too disruptive, I'd love to include built-in support for Langfuse (and/or other LLM monitoring libraries)

**Comment by galatolofederico** [comment]
Solved in  #18
