### ISSUE TITLE
what is the template?

### ISSUE THREAD

**Issue by JINO-ROHIT** [galatolofederico/microchain#4]
template = HFChatTemplate(os.environ["TEMPLATE_NAME"])

what is this template? is there a sample .env for this? i cant wrap my head around this

**Comment by galatolofederico** [comment]
Hi, it applies a chat template using `apply_chat_template` from the
specified Huggingface model.

In the example `TEMPLATE_NAME` is the name of the model on hf

Il gio 28 dic 2023, 05:47 JINO ROHIT ***@***.***> ha scritto:

**Comment by galatolofederico** [comment]
Hi, it applies a chat template using `apply_chat_template` from the specified Huggingface model. 

In the example `TEMPLATE_NAME` is the name of the model on hf
